coinbase/terraform-landscape

lib/terraform_landscape/printer.rb

The tool assumed we were using the `-out` flag to specify an output
file, which would result in `Path: ...` appearing in Terraform's output.
Since we don't want to require the use of the `-out` flag, improve the
preface detection to handle this case. Also handle the case where there
are no changes detected.

Handle empty output and no explicit -out flag

---

CHANGELOG.md
lib/terraform_landscape/version.rb

We've fixed a bug that prevented `landscape` from working out of the box when running `terraform plan`. With a fix in place, we're now ready for a "0.1" release.
Also add a change log so we better track changes going forward.

Cut version 0.1.0

---

terraform_landscape.gemspec

Fixes the following warning when we build the gem:
WARNING:  license value 'Apache 2.0' is invalid.  Use a license
identifier from http://spdx.org/licenses or 'Nonstandard' for a
nonstandard license.

Fix gem license type format

---

CHANGELOG.md
lib/terraform_landscape/terraform_plan.rb
lib/terraform_landscape/version.rb
spec/terraform_plan_spec.rb

Our grammar assumes Unix newlines, so replace Windows newlines before attempting to parse.

Fix windows line endings and cut new release

---

lib/terraform_landscape/printer.rb
spec/printer_spec.rb

`terraform show` output doesn't contain the postface, and it'd
be nice to be able to landscape over pre-generated plans.

Printer: add option to ignore postfaces

---

CHANGELOG.md
grammar/terraform_plan.treetop
lib/terraform_landscape/version.rb

Terraform 0.10.0 changed the output format to include additional indentation for resource changes. Modify our grammar to support it.

Gracefully handle new output format of Terraform 0.10.0

---

CHANGELOG.md
grammar/terraform_plan.treetop
spec/terraform_plan_spec.rb

Hi there!
I noticed an issue in which `landscape` assumes that attribute names cannot have spaces in them, where in fact they can. For instance, with `aws_cloudwatch_metric_alarm` [resources](https://www.terraform.io/docs/providers/aws/r/cloudwatch_metric_alarm.html), the `dimension` attribute can have keys that have spaces.
Let me know if this will result in any other issues.
Thanks for putting together this awesome gem!

Fixed bug in which attribute names cannot have whitespace

---

grammar/terraform_plan.treetop
lib/terraform_landscape/printer.rb
lib/terraform_landscape/terraform_plan.rb
spec/printer_spec.rb
spec/terraform_plan_spec.rb

With Terraform v0.10.4, the output of `terraform plan` has changed in two ways
which `terraform-landscape` needed updating:
1. The preface to the plan includes a new header which includes a legend to
explain the actions are creating/updating/removing resources.
2. The output of computed fields has changed to no longer be `<computed>` within
quotes.
This addresses the two updates as follows:
1. Updates `Printer` to scrub for the new preface and skip the
legend. Previously, the legend was being processed as a resource, but didn't
match the resource name pattern.
2. Updates the treetop grammar definition to perform some value sanitization, as
this was the easiest place to centrally handle the permutations it might
encounter.
Added numerous tests to account for forwards and backwards …

Updates handling for newer `terraform plan` output

---

grammar/terraform_plan.treetop
spec/terraform_plan_spec.rb

This fixes an issue with processing resource attribute names that included
colons. This is primarily possible when a tag name includes a colon.
The issue is with the parser grammer only matching an attribute name up until
the colon. It was then failing to evaluate the content since it included extra
data. This changes it to use a lookahead matcher to look for `: `.
Note that this still will be a problem if tag names are using `: `, however I'm
unsure if treetop can do a regex that matches the last occurrance within a line.
FYI @tmatilai 
Fixes #32

Fixes an issue with processing attribute names that include colons.

---

lib/terraform_landscape/printer.rb

Handle `terraform show tf.plan | landscape` 
Terraform Output: 
```
This plan does nothing.
```
https://github.com/hashicorp/terraform/blob/master/command/format/plan.go#L174
We're using terraform show on a generated plan and sending the output through landscape.
The `This plan does nothing` message is the equivalent of the `No changes` message.

Handle Terraform show output: `This plan does nothing`

---

grammar/terraform_plan.treetop
spec/terraform_plan_spec.rb

This updates the previous change to handle Terraform outputting `<computed>`
fields without quotes to include other possible values. This was also breaking
for `<sensitive>` fields, such as when launching new RDS instances and defining
the password.
This changes it to just handle generic content so it isn't hardcoded to specific
values.

Update the support for unquoted bracketed output.

---

lib/terraform_landscape/printer.rb
spec/printer_spec.rb

When running against plans which contained the output of `terraform
init` we would fail due to the `-` being seen as a resource deletion.
Fix by ignoring in the case where the line ends with `...`.

Ignore initialization messages

---

CHANGELOG.md
lib/terraform_landscape/printer.rb
lib/terraform_landscape/version.rb
spec/printer_spec.rb

Fix handling of dashed line separators after refresh output

---

.github/CONTRIBUTING.md
Gemfile
Guardfile
lib/terraform_landscape/output.rb
lib/terraform_landscape/printer.rb
spec/printer_spec.rb
spec/spec_helper.rb

This doesn't try and get too clever with the parser, but it does handle `terraform apply` relatively well.
I think this approach could be extended a bit with some refactoring to pass-through the progress output from terraform commands, and only parse & redisplay the "meat" of the plan itself.
This implements the second strategy mentioned in https://github.com/coinbase/terraform-landscape/issues/53#issuecomment-392192553
I've done some local testing with the binaries on the shell, and the rspec test seems to cover the happy path.

Sort-of handle `terraform apply`

---

lib/terraform_landscape/printer.rb
spec/printer_spec.rb

I think that output should maintain compatibility when to be used via any other terraform analyze tool.
For example, I use [tfnotify](https://github.com/mercari/tfnotify) that enables to notify terraform diff on GitHub pr.
In our use case, we want to checks without `terraform plan` manually because it is not efficient to do it and comment its result to github.
```
terraform plan | landscape | tfnotify plan
```
In this pr, I kept the change to minimum.

'No changes' output with period 'No changes.'

---

lib/terraform_landscape/printer.rb

When using workspace feature in terraform, `terraform apply` prompt looks like
> Do you want to perform these actions in workspace "WORKSPACE"?
, so existing regex would not work. This patch fixes it.

Fix landscape hangs infintely on apply when using workspaces.

---

lib/terraform_landscape/printer.rb

Currently landscape read output in unit of 1024bytes. When buffer contains only part of 3-byte UTF-8 character, this causes ArgumentError when matching with regex.
For example, `갱` is 3byte UTF-8 character "\xEA\xB0\xB1" and valid, but "\xEA\xB0" is invalid UTF8 string.
This PR fixes this problem by replacing invalid UTF8 character to empty string.

Fix error when buffer contains only part of 3byte UTF-8 characters.

---

lib/terraform_landscape/terraform_plan.rb
spec/terraform_plan_spec.rb
terraform_landscape.gemspec

Issue: #62 
As you can see from Issue # 62, using eval expands the value like "#{host}".
So instead of using eval we change it to parse attribute value using regular expression and string_undump.
Since String # undump is a method introduced from Ruby 2.5, we will make it work with Ruby 2+ by using the string_undump package.

Fix fail parse attribute value

---

lib/terraform_landscape/printer.rb
spec/printer_spec.rb

It fixes output like this:
```
Initializing modules...
- module.base_network
Getting source "../modules/base_network"
- module.ecs_service
Found version 0.3.0 of ecs-service on registry.terraform.io
Getting source "ecs-service"
```

Remove initialization messages like "- module.base_network"

---

lib/terraform_landscape/terraform_plan.rb
spec/terraform_plan_spec.rb

`String#undump` is a function that does the reverse of `String#dump`, so we expect `String#dump` output.
Multibyte characters in `terraform_pran` results are not escaped. They differ from the results of `String#dump` (`String#dump` converts non ASCII characters to Unicode escape sequences).
example:
```ruby
puts 'hello, 世界'.dump              # => "hello, \u4E16\u754C"
puts '"hello, \u4E16\u754C"'.undump # => hello, 世界
puts '"hello, 世界"'
```

Support non ASCII attribute

---

lib/terraform_landscape/cli.rb
lib/terraform_landscape/printer.rb

Our preprocessing step was resulting in a bug where we would fail to parse a valid plan. This wasn't caught earlier because the particular confluence of items present in the plan (initialization of modules + no changes) was never exercised.
While here, since it was useful in debugging we added support for specifying an output file via CLI argument.
This allows you to pass in a file not via stdin.
---
When we preprocess the input, our regex patterns only work with Unix
newlines.
---

Fix handling of Windows newlines
